# Generated by Django 3.2.4 on 2021-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cover',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo90D-727qw6WMKpUCl0mpzBa5TLFqvsTfPg&usqp=CAU', max_length=500),
        ),
        migrations.AddField(
            model_name='inscription',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
