# Generated by Django 3.2.4 on 2021-07-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_inscription_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
