# Generated by Django 3.2.4 on 2021-07-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_inscription_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', width_field=300)),
                ('image_text', models.CharField(max_length=64)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.inscription')),
            ],
        ),
    ]
