# Generated by Django 3.2.4 on 2021-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='InscriptionImages', width_field=300),
        ),
    ]
